name: Build and Deploy Docker Image to Server
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Push Docker Image to Docker Hub and Deploy to Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        id: docker-hub
        run: |
          docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build the Docker Image
        id: build-docker-image
        run: |
          ls -la
          docker build . -f Dockerfile -t ${{secrets.DOCKER_USERNAME}}/webportfolio:latest

      - name: Push the Docker Image
        id: push-docker-image
        run: docker push ${{secrets.DOCKER_USERNAME}}/webportfolio:latest

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # Ensure VPS_HOSTNAME is set correctly
          echo "Checking VPS_HOSTNAME: $VPS_HOSTNAME"
          
          # Add the server to known hosts using ssh-keyscan
          ssh-keyscan -H $VPS_HOSTNAME >> ~/.ssh/known_hosts
          
          # Start the SSH agent and add the private key
          eval $(ssh-agent -s)
          echo "$SSH_PRIVATE_KEY" | ssh-add -

        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_HOSTNAME: ${{ secrets.VPS_HOSTNAME }}  # Make sure you have this secret

      - name: Connect to server via SSH
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -o GSSAPIAuthentication=no username@$VPS_HOSTNAME "echo 'Connected successfully!'"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_HOSTNAME: ${{ secrets.VPS_HOSTNAME }}
