name: Build and Deploy Docker Image to Server

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Vitest
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Run Tests
        run: npm run test

  build-deploy:
    name: Build and Deploy Docker Image to Server
    runs-on: ubuntu-latest
    needs: test  # This ensures the build only runs if tests pass
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker Image
        run: |
          docker build . -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/webportfolio:latest

      - name: Push the Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/webportfolio:latest

      - name: Set up SSH key for server connection
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Connect to server via SSH and deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Stop and remove any existing containers
            sudo docker stop $(sudo docker ps -aq) || true
            sudo docker rm $(sudo docker ps -aq) || true

            # Pull the latest image from Docker Hub
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/webportfolio:latest

            # Make sure your SSL certificates are already on the server
            # For example, /etc/ssl/private/ssl.key and /etc/ssl/certs/ssl.crt
            # If you need to put them there, you can do so outside of this script
            # or via scp, rsync, or some other secure method. DO NOT just echo secrets in plain text.

            # Run the container with volumes mapping your existing SSL cert/key on the host
            sudo docker run -d \
              --name webportfolio \
              -p 80:80 \
              -p 443:443 \
              -v /etc/ssl/private/ssl.key:/etc/ssl/private/ssl.key:ro \
              -v /etc/ssl/certs/ssl.crt:/etc/ssl/certs/ssl.crt:ro \
              ${{ secrets.DOCKER_USERNAME }}/webportfolio:latest
