name: Build and Deploy Docker Image to Server
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Push Docker Image to Docker Hub and Deploy to Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build the Docker Image
        run: |
          docker build . -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/webportfolio:latest

      - name: Push the Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/webportfolio:latest

      - name: Set up SSH key for server connection
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Save SSL Certificates
        run: |
          echo "${{ secrets.SSL_PRIVATE_KEY }}" > ssl.key
          echo "${{ secrets.SSL_CERT_CHAIN }}" > ssl.crt
          chmod 600 ssl.key ssl.crt

      - name: Connect to server via SSH and deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker stop $(sudo docker ps -aq) || true
            sudo docker rm $(sudo docker ps -aq) || true
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/webportfolio:latest
            sudo docker run -d -p 80:80 -p 443:443 --name webportfolio \
              -v $(pwd)/ssl.key:/app/ssl.key \
              -v $(pwd)/ssl.crt:/app/ssl.crt \
              -e SSL_PRIVATE_KEY="/app/ssl.key" \
              -e SSL_CERT_CHAIN="/app/ssl.crt" \
              ${{ secrets.DOCKER_USERNAME }}/webportfolio:latest
