name: Build and Deploy Docker Image to Server
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Push Docker Image to Docker Hub and Deploy to Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        id: docker-hub
        run: |
          docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build the Docker Image
        id: build-docker-image
        run: |
          ls -la
          docker build . -f Dockerfile -t ${{secrets.DOCKER_USERNAME}}/webportfolio:latest

      - name: Push the Docker Image
        id: push-docker-image
        run: docker push ${{secrets.DOCKER_USERNAME}}/webportfolio:latest

      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: Connect to server via SSH
        run: |
          sshpass -p ${{secrets.VPS_PASSWORD}} ssh -o StrictHostKeyChecking=no ${{secrets.VPS_USERNAME}}@${{secrets.VPS_HOST}}
          sudo docker stop $(sudo docker ps -aq) || true
          sudo docker rm $(sudo docker ps -aq) || true
          sudo docker pull htdguide/webportfolio
          sudo docker run -d -p 5173:5173 htdguide/webportfolio
